#!/bin/bash

# ═══════════════════════════════════════════════════════════════════════════
# 🔐 SCRIPT RÁPIDO - ACTIVAR AUTENTICACIÓN ADMIN
# ═══════════════════════════════════════════════════════════════════════════

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║         🔐 GUÍA RÁPIDA - CONFIGURAR ACCESO AL PANEL ADMIN             ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 ESTADO ACTUAL:"
echo "✅ Código del endpoint /api/login CORREGIDO"
echo "✅ Migración 005 CREADA (pero no aplicada)"
echo "❌ Base de datos SIN contraseñas hashadas"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo "PASO 1️⃣ : APLICAR MIGRACIÓN EN SUPABASE (MANUAL)"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Ir a: https://supabase.com/dashboard"
echo "2. Seleccionar proyecto 'yaja-admin-panel'"
echo "3. Ir a SQL Editor → New Query"
echo "4. Copiar TODO el contenido de:"
echo "   📄 migrations/005_fix_admin_user_auth.sql"
echo "5. Pegar en SQL Editor"
echo "6. Click en 'Run' (o Ctrl+Enter)"
echo "7. Debe aparecer: ✅ INSERT 0 3"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo "PASO 2️⃣ : PROBAR CREDENCIALES"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "Después de ejecutar la migración:"
echo ""
echo "🌐 URL: http://localhost:3000/admin-login"
echo ""
echo "📧 Email: admin@yaja.mx"
echo "🔑 Password: admin123"
echo ""
echo "Si funciona → Redirige a /dashboard ✅"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo "📝 OTRAS CREDENCIALES DISPONIBLES:"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "👤 Gestor:"
echo "   Email: manager@yaja.mx"
echo "   Pass: manager123"
echo ""
echo "👤 Operador:"
echo "   Email: operator@yaja.mx"
echo "   Pass: operator123"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo "🆘 SI NO FUNCIONA:"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "1. Verificar en Supabase SQL Editor:"
echo "   SELECT COUNT(*) FROM \"AdminUser\""
echo "   Debe retornar: 3"
echo ""
echo "2. Verificar que password_hash existe:"
echo "   \d \"AdminUser\""
echo "   Debe listar: password_hash | text"
echo ""
echo "3. Revisar logs del servidor:"
echo "   npm run dev"
echo "   Buscar: [API LOGIN]"
echo ""
echo "4. Revisar Developer Tools (F12):"
echo "   Console tab para errores"
echo "   Network tab para ver request a /api/login"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════"
echo "✨ LISTO"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 Documentación completa en:"
echo "   📄 ADMIN_ACCESS_GUIDE.md"
echo "   📄 AUTH_SETUP_SUMMARY.md"
echo ""
