#!/bin/bash
# Quick Verification Script for Company Migration

echo "🔍 Verificación Rápida de Migración - Company"
echo "=============================================="
echo ""
echo "Para verificar que la migración fue exitosa, ejecuta esto en Supabase SQL Editor:"
echo ""
echo "📋 CONSULTA DE VERIFICACIÓN:"
echo "---"
echo "SELECT column_name, data_type, is_nullable, column_default"
echo "FROM information_schema.columns"
echo "WHERE table_name = 'Company'"
echo "AND column_name IN ("
echo "  'zone_prices', 'folio_fields', 'folio_secundario_fields', 'sub_accounts',"
echo "  'tax_pct', 'billing_type', 'survey_id', 'parent_company_id', 'sub_company_limit'"
echo ")"
echo "ORDER BY ordinal_position;"
echo "---"
echo ""
echo "✅ Resultado esperado: 9 filas"
echo ""
echo "📍 Ubicación: https://app.supabase.com"
echo "   → Selecciona proyecto: YAJA"
echo "   → SQL Editor → New Query"
echo "   → Pega la consulta arriba"
echo "   → Haz clic en ▶ Run"
echo ""
echo "Para más detalles, abre: VERIFICATION_CHECKLIST.md"
echo ""
